# NumPy Examples

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = np.array([1,2,3,4])

In [6]:
#documentation
np.array?

In [7]:
a1 = [1,2,3,4]
print(type(a1))

a2 = np.array(a1)

print(a2)

<class 'list'>
[1 2 3 4]


In [8]:
a3 = [1, 2, "three", "four"]
a4 = np.array(a3)

In [9]:
print(a4)

['1' '2' 'three' 'four']


In [10]:
a4 = np.array([1,2, "3", "4"], dtype=np.int16)

In [11]:
print(a4)

[1 2 3 4]


In [12]:
a5 = np.array([[1.,0.,0.], [4., 7., 0.]])
print(a5)
print(type(a5))
print(a5.dtype)

[[1. 0. 0.]
 [4. 7. 0.]]
<class 'numpy.ndarray'>
float64


# Attributes

In [13]:
# rows, columns
a5.shape

(2, 3)

In [14]:
# rows times columns
a5.size

6

In [15]:
# values in the array are of type
a5.dtype

dtype('float64')