# NumPy Examples

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = np.array([1,2,3,4])

In [6]:
#documentation
np.array?

In [7]:
a1 = [1,2,3,4]
print(type(a1))

a2 = np.array(a1)

print(a2)

<class 'list'>
[1 2 3 4]


In [8]:
a3 = [1, 2, "three", "four"]
a4 = np.array(a3)

In [9]:
print(a4)

['1' '2' 'three' 'four']


In [10]:
a4 = np.array([1,2, "3", "4"], dtype=np.int16)

In [11]:
print(a4)

[1 2 3 4]


In [12]:
a5 = np.array([[1.,0.,0.], [4., 7., 0.]])
print(a5)
print(type(a5))
print(a5.dtype)

[[1. 0. 0.]
 [4. 7. 0.]]
<class 'numpy.ndarray'>
float64


# Attributes

In [13]:
# rows, columns
a5.shape

(2, 3)

In [14]:
# rows times columns
a5.size

6

In [15]:
# values in the array are of type
a5.dtype

dtype('float64')

# Indexing, Slicing and Iterating

In [16]:
array_1 = np.array([1,2,3,4,5,6,7,8])
print(array_1)

[1 2 3 4 5 6 7 8]


In [17]:
array_1[0]

1

In [18]:
array_1[-1]

8

In [19]:
array_2 = np.array([[1,2,3],[4,5,6]])

In [20]:
array_2[1,1]

5

In [21]:
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
for element in array_2:
    print(element)

[1 2 3]
[4 5 6]


In [24]:
for element in array_2.flat:
    print(element)

1
2
3
4
5
6


# Manipulating Arrays

In [25]:
array_1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
array_1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
array_1.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
array_2 = np.array(range(1,10))

In [29]:
array_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array_2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array_2.reshape(3,2) #can't reshape array of size nine this way

ValueError: cannot reshape array of size 9 into shape (3,2)

In [ ]:
array_3 = np.array([1,2,3,4])