# NumPy Examples

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = np.array([1,2,3,4])

In [6]:
#documentation
np.array?

In [7]:
a1 = [1,2,3,4]
print(type(a1))

a2 = np.array(a1)

print(a2)

<class 'list'>
[1 2 3 4]


In [8]:
a3 = [1, 2, "three", "four"]
a4 = np.array(a3)

In [9]:
print(a4)

['1' '2' 'three' 'four']


In [10]:
a4 = np.array([1,2, "3", "4"], dtype=np.int16)

In [11]:
print(a4)

[1 2 3 4]


In [12]:
a5 = np.array([[1.,0.,0.], [4., 7., 0.]])
print(a5)
print(type(a5))
print(a5.dtype)

[[1. 0. 0.]
 [4. 7. 0.]]
<class 'numpy.ndarray'>
float64


# Attributes

In [13]:
# rows, columns
a5.shape

(2, 3)

In [14]:
# rows times columns
a5.size

6

In [15]:
# values in the array are of type
a5.dtype

dtype('float64')

# Indexing, Slicing and Iterating

In [16]:
array_1 = np.array([1,2,3,4,5,6,7,8])
print(array_1)

[1 2 3 4 5 6 7 8]


In [17]:
array_1[0]

1

In [18]:
array_1[-1]

8

In [19]:
array_2 = np.array([[1,2,3],[4,5,6]])

In [20]:
array_2[1,1]

5

In [21]:
array_2

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
for element in array_2:
    print(element)

[1 2 3]
[4 5 6]


In [24]:
for element in array_2.flat:
    print(element)

1
2
3
4
5
6


# Manipulating Arrays

In [25]:
array_1.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
array_1.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [27]:
array_1.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [28]:
array_2 = np.array(range(1,10))

In [29]:
array_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
array_2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
array_2.reshape(3,2) #can't reshape array of size nine this way

ValueError: cannot reshape array of size 9 into shape (3,2)

In [32]:
array_3 = np.array([1,2,3,4,5,6,7,8])
print(array_3.reshape(2,2,-1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
array_3.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
array_3.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

# Creating Arrays Using Functions

In [36]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [39]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [40]:
# create sequences of numbers
np.arange(start=10, stop=20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
np.arange(start=10, stop=20, step=2)

array([10, 12, 14, 16, 18])

In [42]:
# get 10 elements between 0 and 5
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [44]:
np.linspace(start=2, stop=10, num=8)

array([ 2.        ,  3.14285714,  4.28571429,  5.42857143,  6.57142857,
        7.71428571,  8.85714286, 10.        ])

In [45]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [47]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(4,k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# Array Operations

In [49]:
array_1 = np.array([[10,5,1],[4,3,2]])
array_2 = np.array([[9,4,1],[3,2,2]])
array_1 - array_2

array([[1, 1, 0],
       [1, 1, 0]])

In [50]:
array_1 * 2

array([[20, 10,  2],
       [ 8,  6,  4]])

In [51]:
array_1 > 1

array([[ True,  True, False],
       [ True,  True,  True]])

In [54]:
array_3 = np.array([range(0,2), range(1,3)])
print ("array 3:")
print(array_3)

array_4 = np.array((1,1))
print ("array 4:")
print(array_4)

array 3:
[[0 1]
 [1 2]]
array 4:
[1 1]


In [55]:
array_3 @ array_4

array([1, 3])

In [56]:
array_3.dot(array_4)

array([1, 3])

In [57]:
np.matrix()

TypeError: __new__() missing 1 required positional argument: 'data'